blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/stavros-it/PlayCache/discussions
    about: For questions and help, please use Discussions instead of opening an issue.
